version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"   # Qdrant REST API
      - "6334:6334"   # Qdrant gRPC (optional)
    volumes:
      - ./qdrant/storage:/qdrant/storage   # Persistent storage
    restart: unless-stopped
